# Generated by Django 2.1.2 on 2018-10-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20181013_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='facebook_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='friends_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='steam_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
