# Generated by Django 2.1.2 on 2018-10-13 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_bot_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='mailing',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='website.Mailing'),
        ),
    ]
